baseURL = 'https://github.com/AlexandraOreza/ommyuc.git'
languageCode = 'es'
title = 'OMM Yucat√°n'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10

[params.docs]
    darkMode = true