baseURL = 'https://github.com/AlexandraOreza/ommyuc'
languageCode = 'en-GB'
title = 'OMM Yucat√°n'

defaultContentLanguage = 'es'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name  = "Material"
    url = "/docs/material/"
    identifier = "mats"
    weight = 10
[[menu.primary]]
    name  = "Sobre la Olimpiada"
    url = "/docs/info/"
    identifier = "info"
    weight = 20

[params.docs]
    darkMode = true